language: android
jdk: oraclejdk8
os: linux

before_cache:
 - rm -rf $HOME/.gradle/caches/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

env:
 global:
 - ANDROID_API=29
 - ANDROID_BUILD_TOOLS=29.0.2

android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 
 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+

before_install:
- chmod +x gradlew

script:
- "./gradlew build --stacktrace"